<?php

namespace HTM\FilmoBundle\Repository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFilmsByCategorie($categorie){
        $query = $this->createQueryBuilder('f')
           ->where('f.categorie = :categorie')
           ->setParameter('categorie', $categorie)
           ->orderBy('f.titre', 'ASC')
           ->getQuery();

       $films = $query->getResult();
       return $films;
    }
}
