htm_filmo:
    resource: "@HTMFilmoBundle/Controller/"
    type:     annotation
    prefix:   /

htm_user:
    resource: "@HTMUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
